name: Sync Repo

on:
  schedule:
    - cron: 8 20 * * *
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    env:
      repoUrl: https://github.com/hjdhnx/dr_py.git
      repoBranch: main
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ env.repoBranch }}
      - name: Set env
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
      - name: Update fork
        run: |
          git remote add upstream ${{ env.repoUrl }}
          git remote -v
          git fetch upstream
          git checkout ${{ env.repoBranch }}
          git merge upstream/${{ env.repoBranch }}
          git push origin ${{ env.repoBranch }}
